#!/bin/bash

UNITTESTS_DIR="tests/"

#echo "Running unittests."
python3 -m unittest discover $UNITTESTS_DIR > /dev/null || {
    echo "Unittests DID NOT pass!"
    echo "Fix code or use --no-verify."
    exit 1
}

#echo "Running autopep8"
PEP8_PROBLEMS=`python3-autopep8 -r --diff .`
if [ -n "$PEP8_PROBLEMS" ]
then
    echo "NOT PEP 8 compliant, suggested diff:"
    echo "$PEP8_PROBLEMS"
    echo "Fix code or use --no-verify."
    exit 1
fi

#echo "Running pyflakes check."
python3 -m pyflakes . || {
    echo "Pyflakes COMPLAINS!"
    echo "Fix code or use --no-verify."
    exit 1
}

#echo "Ready to commit !"
exit 0
