language: python

python:
  - "3.4"
  - "3.6"
  - "nightly"

addons:
  apt:
    packages:
    - colordiff

install:
  - "pip install autopep8 flake8 flake8-colors pytest beautifulsoup4 requests
  - "pip install -e ."

script:
 - make test

notifications:
  email: false
